#!/usr/bin/env bun
/**
 * Screenshot script for generating DevProc screenshots and demo GIFs using VHS
 *
 * Usage:
 *   bun run scripts/screenshot.ts              # Generate screenshot
 *   bun run scripts/screenshot.ts --gif        # Also generate demo GIF
 *   bun run scripts/screenshot.ts --no-docker  # Skip docker compose services
 *   bun run scripts/screenshot.ts --theme X    # Use a different theme
 *   bun run scripts/screenshot.ts --help       # Show help
 */

import { $ } from "bun"
import { mkdir, rm, copyFile } from "fs/promises"
import { existsSync } from "fs"
import { join } from "path"

// Configuration - matches screenshot.tape styles
const CONFIG = {
  // Terminal dimensions
  width: 1400,
  height: 800,
  fontSize: 25,
  letterSpacing: 0,

  // Styling
  theme: "tokyonight-storm",
  padding: 20,
  margin: 20,
  marginFill: "#79B8C3",
  borderRadius: 20,
  windowBar: "Colorful",

  // Timing
  startupWait: 12, // seconds to wait for services to start
  screenshotDelay: 2, // seconds after startup before screenshot

  // Output paths
  outputDir: "assets",
  docsOutputDir: "docs/src/assets",
  docsPublicDir: "docs/public",
  screenshotName: "screenshot.png",
  gifName: "demo.gif",
}

// Available themes (curated list of good dark themes)
const RECOMMENDED_THEMES = [
  "tokyonight-storm",
  "tokyonight",
  "Dracula",
  "Catppuccin Mocha",
  "Nord",
  "One Dark",
  "GitHub Dark",
  "Builtin Dark",
]

interface Options {
  gif: boolean
  docker: boolean
  theme: string
  help: boolean
}

function parseArgs(): Options {
  const args = process.argv.slice(2)
  const options: Options = {
    gif: false,
    docker: true,
    theme: CONFIG.theme,
    help: false,
  }

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]
    switch (arg) {
      case "--gif":
        options.gif = true
        break
      case "--no-docker":
        options.docker = false
        break
      case "--theme":
        options.theme = args[++i] || CONFIG.theme
        break
      case "--help":
      case "-h":
        options.help = true
        break
    }
  }

  return options
}

function showHelp() {
  console.log(`
DevProc Screenshot Generator

Usage:
  bun run scripts/screenshot.ts [options]

Options:
  --gif          Also generate a demo GIF showing the TUI in action
  --no-docker    Skip docker compose services (faster, uses only bash services)
  --theme <name> Use a different VHS theme (default: ${CONFIG.theme})
  --help, -h     Show this help message

Recommended themes:
${RECOMMENDED_THEMES.map((t) => `  - ${t}`).join("\n")}

Examples:
  bun run scripts/screenshot.ts
  bun run scripts/screenshot.ts --gif
  bun run scripts/screenshot.ts --no-docker --theme "Dracula"
`)
}

function generateTapeContent(options: Options, outputFile: string): string {
  const command = options.docker ? "devproc" : "devproc"

  return `# DevProc Screenshot Tape
# Generated by scripts/screenshot.ts

# Terminal settings
Set Shell "bash"
Set FontSize ${CONFIG.fontSize}
Set LetterSpacing ${CONFIG.letterSpacing}

Set Width ${CONFIG.width}
Set Height ${CONFIG.height}

Set Padding ${CONFIG.padding}

Set MarginFill "${CONFIG.marginFill}"
Set Margin ${CONFIG.margin}

Set BorderRadius ${CONFIG.borderRadius}

Set Theme "${options.theme}"
Set WindowBar ${CONFIG.windowBar}
Set CursorBlink false

# Hide the initial setup
Hide
Type "cd ${process.cwd()}"
Enter
Sleep 500ms
Type "clear"
Enter
Sleep 500ms
Show

# Start DevProc
Type "${command}"
Enter

# Wait for services to start and logs to appear
Sleep ${CONFIG.startupWait}s

# Small delay to ensure UI is stable
Sleep ${CONFIG.screenshotDelay}s

# Take the screenshot
Screenshot ${outputFile}
`
}

function generateGifTapeContent(options: Options, outputFile: string): string {
  const command = options.docker ? "devproc" : "devproc"

  return `# DevProc Demo GIF Tape
# Generated by scripts/screenshot.ts

# Output
Output ${outputFile}

# Terminal settings
Set Shell "bash"
Set FontSize ${CONFIG.fontSize}
Set LetterSpacing ${CONFIG.letterSpacing}

Set Width ${CONFIG.width}
Set Height ${CONFIG.height}

Set Padding ${CONFIG.padding}

Set MarginFill "${CONFIG.marginFill}"
Set Margin ${CONFIG.margin}

Set BorderRadius ${CONFIG.borderRadius}

Set Theme "${options.theme}"
Set WindowBar ${CONFIG.windowBar}
Set TypingSpeed 50ms
Set CursorBlink false

# Hide the initial setup
Hide
Type "cd ${process.cwd()}"
Enter
Sleep 500ms
Type "clear"
Enter
Sleep 500ms
Show

# Start DevProc with a nice typing effect
Type "${command}"
Sleep 500ms
Enter

# Wait for services to start
Sleep ${CONFIG.startupWait}s

# Show the UI for a moment
Sleep 2s

# Navigate down through services
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms

# Show logs scrolling
Sleep 3s

# Switch to monitoring view
Type "m"
Sleep 3s

# Navigate in monitoring view
Down
Sleep 500ms
Down
Sleep 500ms

# Show monitoring for a bit
Sleep 2s

# Switch back to logs view
Type "m"
Sleep 2s

# Navigate back up
Up
Sleep 500ms
Up
Sleep 500ms

# Final pause
Sleep 2s

# Quit gracefully
Type "q"
Sleep 1s
`
}

async function checkDependencies() {
  try {
    await $`which vhs`.quiet()
  } catch {
    console.error("Error: VHS is not installed.")
    console.error("Install it with: brew install charmbracelet/tap/vhs")
    process.exit(1)
  }

  try {
    await $`which ffmpeg`.quiet()
  } catch {
    console.error("Error: ffmpeg is not installed (required by VHS).")
    console.error("Install it with: brew install ffmpeg")
    process.exit(1)
  }
}

async function ensureDirectories() {
  await mkdir(CONFIG.outputDir, { recursive: true })
  await mkdir(CONFIG.docsOutputDir, { recursive: true })
  await mkdir(CONFIG.docsPublicDir, { recursive: true })
}

async function runVhs(tapeFile: string) {
  console.log(`Running VHS with ${tapeFile}...`)
  try {
    await $`vhs ${tapeFile}`
  } catch (error) {
    console.error("VHS failed:", error)
    throw error
  }
}

async function main() {
  const options = parseArgs()

  if (options.help) {
    showHelp()
    process.exit(0)
  }

  console.log("DevProc Screenshot Generator")
  console.log("============================\n")

  // Check dependencies
  await checkDependencies()
  console.log("Dependencies OK (vhs, ffmpeg)")

  // Ensure output directories exist
  await ensureDirectories()

  const tempDir = ".screenshot-temp"
  await mkdir(tempDir, { recursive: true })

  try {
    // Generate screenshot
    const screenshotOutput = join(CONFIG.outputDir, CONFIG.screenshotName)
    const screenshotTape = join(tempDir, "screenshot.tape")
    const tapeContent = generateTapeContent(options, screenshotOutput)

    await Bun.write(screenshotTape, tapeContent)
    console.log(`\nGenerating screenshot with theme: ${options.theme}`)
    console.log(`Output: ${screenshotOutput}`)

    await runVhs(screenshotTape)

    // Copy to docs directory
    if (existsSync(screenshotOutput)) {
      const docsOutput = join(CONFIG.docsOutputDir, CONFIG.screenshotName)
      await copyFile(screenshotOutput, docsOutput)
      console.log(`Copied to: ${docsOutput}`)
    }

    // Generate GIF if requested
    if (options.gif) {
      const gifOutput = join(CONFIG.outputDir, CONFIG.gifName)
      const gifTape = join(tempDir, "demo.tape")
      const gifTapeContent = generateGifTapeContent(options, gifOutput)

      await Bun.write(gifTape, gifTapeContent)
      console.log(`\nGenerating demo GIF...`)
      console.log(`Output: ${gifOutput}`)

      await runVhs(gifTape)

      // Copy to docs directories (assets for processing, public for static serving)
      if (existsSync(gifOutput)) {
        const docsGifOutput = join(CONFIG.docsOutputDir, CONFIG.gifName)
        const docsPublicGifOutput = join(CONFIG.docsPublicDir, CONFIG.gifName)
        await copyFile(gifOutput, docsGifOutput)
        await copyFile(gifOutput, docsPublicGifOutput)
        console.log(`Copied to: ${docsGifOutput}`)
        console.log(`Copied to: ${docsPublicGifOutput}`)
      }
    }

    console.log("\nDone!")
  } finally {
    // Cleanup temp directory
    await rm(tempDir, { recursive: true, force: true })
  }
}

main().catch((error) => {
  console.error("Error:", error)
  process.exit(1)
})
